### ISSUE TITLE
Running problem of 

### ISSUE THREAD

**Issue by HiAleeYang** [tteepe/GaitGraph2#3]
Hi, I use the command of `python3 gaitgraph_casia_b.py fit --config configs/casia_b.yaml` but get error
Hope you can help me to solve it
Thank you
Sanity Checking DataLoader 0:   0%|                                                                                                                                            | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "gaitgraph_casia_b.py", line 283, in <module>
    cli_main()
  File "gaitgraph_casia_b.py", line 273, in cli_main
    LightningCLI(
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 566, in __init__
    self._run_subcommand(self.subcommand)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 837, in _run_subcommand
    fn(**fn_kwargs)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 154, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 222, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "gaitgraph_casia_b.py", line 77, in validation_step
    y_hat = self(x)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "gaitgraph_casia_b.py", line 64, in forward
    return self.backbone(x)[0]
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fuyang/KeyPoint/GaitGraph2-main/GaitGraph/models/ResGCNv1/nets.py", line 65, in forward
    x_cat.append(branch(x[:, i]))
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fuyang/KeyPoint/GaitGraph2-main/GaitGraph/models/ResGCNv1/nets.py", line 24, in forward
    x = self.bn(x)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/home/fuyang/anaconda3/envs/HID/lib/python3.8/site-packages/torch/nn/functional.py", line 2421, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 5 elements not 15

**Comment by brianw0924** [comment]
Hi, can you share how to fix this error?
