### ISSUE TITLE
error in running code in caisa-b

### ISSUE THREAD

**Issue by aleeyang** [tteepe/GaitGraph2#6]
I use this command `python3 gaitgraph_casia_b.py fit --config configs/casia_b.yaml`
but it always give me error reply

  ```
File "gaitgraph_casia_b.py", line 77, in validation_step
    y_hat = self(x)
  File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "gaitgraph_casia_b.py", line 64, in forward
    return self.backbone(x)[0]
  File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fuyang/project/keypoint/GaitGraph2/GaitGraph2-main/GaitGraph/models/ResGCNv1/nets.py", line 66, in forward
    x_cat.append(branch(x[:, i]))
  File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fuyang/project/keypoint/GaitGraph2/GaitGraph2-main/GaitGraph/models/ResGCNv1/nets.py", line 24, in forward
    x = self.bn(x)
  File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/functional.py", line 2421, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 5 elements not 15
```

**Comment by aleeyang** [comment]
I  can not run your code on caisa-b and oumvlp dataset neither.Can you give more detail command or some steps of configuration? 
thank you very much

**Comment by aleeyang** [comment]
I changed to default setting of caisa-b code `multi_branch: bool = False` to `multi_branch: bool = True`
I get this result from tensorboard,but I do not knoe which result is the finnal one
how can I get the result in your paper from this image? (how can I choose one from these results in different steps?)
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/54769687/172054171-d6ea9a51-3733-4e55-88fb-9486de92ac04.png">

**Comment by OnlyFlashEobard** [comment]
same issue, do you solve it?

> I use this command `python3 gaitgraph_casia_b.py fit --config configs/casia_b.yaml` but it always give me error reply
> 
> ```
> File "gaitgraph_casia_b.py", line 77, in validation_step
>   y_hat = self(x)
> File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>   return forward_call(*input, **kwargs)
> File "gaitgraph_casia_b.py", line 64, in forward
>   return self.backbone(x)[0]
> File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>   return forward_call(*input, **kwargs)
> File "/home/fuyang/project/keypoint/GaitGraph2/GaitGraph2-main/GaitGraph/models/ResGCNv1/nets.py", line 66, in forward
>   x_cat.append(branch(x[:, i]))
> File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>   return forward_call(*input, **kwargs)
> File "/home/fuyang/project/keypoint/GaitGraph2/GaitGraph2-main/GaitGraph/models/ResGCNv1/nets.py", line 24, in forward
>   x = self.bn(x)
> File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>   return forward_call(*input, **kwargs)
> File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
>   return F.batch_norm(
> File "/home/fuyang/anaconda3/envs/gaitgraph/lib/python3.8/site-packages/torch/nn/functional.py", line 2421, in batch_norm
>   return torch.batch_norm(
> RuntimeError: running_mean should contain 5 elements not 15
> ```

same issue, did you solve it?

**Comment by OnlyFlashEobard** [comment]
issue solved

**Comment by zhang123-sys** [comment]
> I changed to default setting of caisa-b code `multi_branch: bool = False` to `multi_branch: bool = True` I get this result from tensorboard,but I do not knoe which result is the finnal one how can I get the result in your paper from this image? (how can I choose one from these results in different steps?) <img alt="image" width="1050" src="https://user-images.githubusercontent.com/54769687/172054171-d6ea9a51-3733-4e55-88fb-9486de92ac04.png">

Could you please send me the result and let me see which result is the final one?

**Comment by D9701** [comment]
> 问题已解决

请问您是怎么解决的呢？可以详细说一下吗？谢谢

**Comment by D9701** [comment]
How did you solve it? Can you elaborate on that? Thank you

**Comment by zhang123-sys** [comment]
> issue solved

Excuse me, what result do you get?

**Comment by xuwenzhengchn** [comment]
> > I changed to default setting of caisa-b code `multi_branch: bool = False` to `multi_branch: bool = True` I get this result from tensorboard,but I do not knoe which result is the finnal one how can I get the result in your paper from this image? (how can I choose one from these results in different steps?) <img alt="image" width="1050" src="https://user-images.githubusercontent.com/54769687/172054171-d6ea9a51-3733-4e55-88fb-9486de92ac04.png">
> 
> Could you please send me the result and let me see which result is the final one?

I changed the default Settings as you said but encountered a new problem. Have you encountered the same problem?


Epoch 0:   0%|                                           | 0/11 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/autodl-tmp/GaitGraph2-main-new/GaitGraph2-main/GaitGraph/gaitgraph_casia_b.py", line 284, in <module>
    cli_main()
  File "/root/autodl-tmp/GaitGraph2-main-new/GaitGraph2-main/GaitGraph/gaitgraph_casia_b.py", line 274, in cli_main
    LightningCLI(
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/cli.py", line 354, in __init__
    self._run_subcommand(self.subcommand)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/cli.py", line 665, in _run_subcommand
    fn(**fn_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 621, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1058, in _run
    results = self._run_stage()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1137, in _run_stage
    self._run_train()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1160, in _run_train
    self.fit_loop.run()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 214, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 200, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 247, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 357, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1302, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1661, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 121, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/optim/adamw.py", line 92, in step
    loss = closure()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 107, in _wrap_closure
    closure_result = closure()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 147, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 133, in closure
    step_output = self._step_fn()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 406, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1440, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 378, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/root/autodl-tmp/GaitGraph2-main-new/GaitGraph2-main/GaitGraph/gaitgraph_casia_b.py", line 70, in training_step
    y_hat = self(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/GaitGraph2-main-new/GaitGraph2-main/GaitGraph/gaitgraph_casia_b.py", line 65, in forward
    return self.backbone(x)[0]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/GaitGraph2-main-new/GaitGraph2-main/GaitGraph/models/ResGCNv1/nets.py", line 60, in forward
    **x = x.permute(0, 3, 4, 1, 2)
RuntimeError: number of dims don't match in permute**
Exception ignored in: <function tqdm.__del__ at 0x7fcc20f945e0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1152, in __del__
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1306, in close
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1499, in display
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1155, in __str__
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1457, in format_dict
TypeError: cannot unpack non-iterable NoneType object

Process finished with exit code 1

**Comment by AhsanBilal7** [comment]
> How did you solve it? Can you elaborate on that? Thank you

Changing  `multi_branch: bool = False` to `multi_branch: bool = True` in the both `GaitGraphCASIAB` and `CASIAPoseModule` Object
