### ISSUE TITLE
torch-geometric version

### ISSUE THREAD

**Issue by zhang123-sys** [tteepe/GaitGraph2#8]
root@Ic479e91c301201ee1:/hy-nas/GaitGraph2-main/GaitGraph# python3 gaitgraph_casia_b.py fit --config configs/casia_b.yaml
Traceback (most recent call last):
  File "gaitgraph_casia_b.py", line 8, in <module>
    from torch_geometric.data import Data
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/data.py", line 9, in <module>
    from torch_sparse import SparseTensor
  File "/usr/local/lib/python3.8/dist-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/usr/local/lib/python3.8/dist-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.8/dist-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_S2_
![image](https://user-images.githubusercontent.com/63956071/178132408-d4488e46-7999-4986-8cca-ebbca117796c.png)

**Comment by zhang123-sys** [comment]
I use this command **python3 gaitgraph_casia_b.py fit --config configs/casia_b.yaml**
but it always give me error reply
```
Traceback (most recent call last):
File "gaitgraph_casia_b.py", line 8, in
from torch_geometric.data import Data
File "/usr/local/lib/python3.8/dist-packages/torch_geometric/init.py", line 4, in
import torch_geometric.data
File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/init.py", line 1, in
from .data import Data
File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/data.py", line 9, in
from torch_sparse import SparseTensor
File "/usr/local/lib/python3.8/dist-packages/torch_sparse/init.py", line 19, in
torch.ops.load_library(spec.origin)
File "/usr/local/lib/python3.8/dist-packages/torch/_ops.py", line 104, in load_library
ctypes.CDLL(path)
File "/usr/lib/python3.8/ctypes/init.py", line 373, in init
self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.8/dist-packages/torch_sparse/_version_cuda.so: undefined symbol: ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_S2
```
