### ISSUE TITLE
RuntimeError: running_mean should contain 5 elements not 15

### ISSUE THREAD

**Issue by brianw0924** [tteepe/GaitGraph2#9]
/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/utilities/cli.py:896: UserWarning: Failed parsing docstring for <function Trainer.fit at 0x7f164af54dc0>: docstring-parser package is required
  rank_zero_warn(f"Failed parsing docstring for {component}: docstring-parser package is required")
/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/utilities/cli.py:896: UserWarning: Failed parsing docstring for <function Trainer.validate at 0x7f164af55000>: docstring-parser package is required
  rank_zero_warn(f"Failed parsing docstring for {component}: docstring-parser package is required")
/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/utilities/cli.py:896: UserWarning: Failed parsing docstring for <function Trainer.test at 0x7f164af55240>: docstring-parser package is required
  rank_zero_warn(f"Failed parsing docstring for {component}: docstring-parser package is required")
/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/utilities/cli.py:896: UserWarning: Failed parsing docstring for <function Trainer.predict at 0x7f164af55480>: docstring-parser package is required
  rank_zero_warn(f"Failed parsing docstring for {component}: docstring-parser package is required")
/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/utilities/cli.py:896: UserWarning: Failed parsing docstring for <function Trainer.tune at 0x7f164af55630>: docstring-parser package is required
  rank_zero_warn(f"Failed parsing docstring for {component}: docstring-parser package is required")
Global seed set to 5318008
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type            | Params
-----------------------------------------------
0 | backbone   | ResGCN          | 255 K 
1 | distance   | LpDistance      | 0     
2 | train_loss | SupConLoss      | 0     
3 | val_loss   | ContrastiveLoss | 0     
-----------------------------------------------
255 K     Trainable params
0         Non-trainable params
255 K     Total params
1.023     Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                                                                                             | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/brianw0924/Desktop/GaitGraph2/GaitGraph/gaitgraph_casia_b.py", line 287, in <module>
    cli_main()
  File "/home/brianw0924/Desktop/GaitGraph2/GaitGraph/gaitgraph_casia_b.py", line 277, in cli_main
    LightningCLI(
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/utilities/cli.py", line 566, in __init__
    self._run_subcommand(self.subcommand)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/utilities/cli.py", line 837, in _run_subcommand
    fn(**fn_kwargs)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_train
    self._run_sanity_check()
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1413, in _run_sanity_check
    val_loop.run()
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 128, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 226, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/brianw0924/Desktop/GaitGraph2/GaitGraph/gaitgraph_casia_b.py", line 81, in validation_step
    y_hat = self(x)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/brianw0924/Desktop/GaitGraph2/GaitGraph/gaitgraph_casia_b.py", line 68, in forward
    return self.backbone(x)[0]
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/brianw0924/Desktop/GaitGraph2/GaitGraph/models/ResGCNv1/nets.py", line 65, in forward
    x_cat.append(branch(x[:, i]))
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/brianw0924/Desktop/GaitGraph2/GaitGraph/models/ResGCNv1/nets.py", line 24, in forward
    x = self.bn(x)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/home/brianw0924/anaconda3/envs/GaitGraph2/lib/python3.10/site-packages/torch/nn/functional.py", line 2421, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 5 elements not 15

I run

python gaitgraph_casia_b.py fit --config configs/casia_b.yaml

and get this

Hi, can you please tell me how to fix this error?

**Comment by shekarneo** [comment]
https://github.com/tteepe/GaitGraph2/issues/6#issue-1260954563

**Comment by SIXZERO65** [comment]
Have you solved this issue?How to?
